<?php
declare(strict_types=1);

// UvIndexApi2 SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

UvIndexApi2Utility::setRegistrar(function (UvIndexApi2Utility $u): void {
    $u->clean = [UvIndexApi2Clean::class, 'call'];
    $u->done = [UvIndexApi2Done::class, 'call'];
    $u->make_error = [UvIndexApi2MakeError::class, 'call'];
    $u->feature_add = [UvIndexApi2FeatureAdd::class, 'call'];
    $u->feature_hook = [UvIndexApi2FeatureHook::class, 'call'];
    $u->feature_init = [UvIndexApi2FeatureInit::class, 'call'];
    $u->fetcher = [UvIndexApi2Fetcher::class, 'call'];
    $u->make_fetch_def = [UvIndexApi2MakeFetchDef::class, 'call'];
    $u->make_context = [UvIndexApi2MakeContext::class, 'call'];
    $u->make_options = [UvIndexApi2MakeOptions::class, 'call'];
    $u->make_request = [UvIndexApi2MakeRequest::class, 'call'];
    $u->make_response = [UvIndexApi2MakeResponse::class, 'call'];
    $u->make_result = [UvIndexApi2MakeResult::class, 'call'];
    $u->make_point = [UvIndexApi2MakePoint::class, 'call'];
    $u->make_spec = [UvIndexApi2MakeSpec::class, 'call'];
    $u->make_url = [UvIndexApi2MakeUrl::class, 'call'];
    $u->param = [UvIndexApi2Param::class, 'call'];
    $u->prepare_auth = [UvIndexApi2PrepareAuth::class, 'call'];
    $u->prepare_body = [UvIndexApi2PrepareBody::class, 'call'];
    $u->prepare_headers = [UvIndexApi2PrepareHeaders::class, 'call'];
    $u->prepare_method = [UvIndexApi2PrepareMethod::class, 'call'];
    $u->prepare_params = [UvIndexApi2PrepareParams::class, 'call'];
    $u->prepare_path = [UvIndexApi2PreparePath::class, 'call'];
    $u->prepare_query = [UvIndexApi2PrepareQuery::class, 'call'];
    $u->graphql_body = [UvIndexApi2Graphql::class, 'body'];
    $u->graphql_errors = [UvIndexApi2Graphql::class, 'errors'];
    $u->result_basic = [UvIndexApi2ResultBasic::class, 'call'];
    $u->result_body = [UvIndexApi2ResultBody::class, 'call'];
    $u->result_headers = [UvIndexApi2ResultHeaders::class, 'call'];
    $u->transform_request = [UvIndexApi2TransformRequest::class, 'call'];
    $u->transform_response = [UvIndexApi2TransformResponse::class, 'call'];
});
